### ISSUE TITLE
图片挂载的地方出现问题。路径需要进行更改。

### ISSUE THREAD

**Issue by wqelinyueting** [TerraMours/TerraMours_Gpt_Web#34]
volumes:
      # 图片挂载地址，将容器中的图片挂载出来
      - F:\Docker\terra\server\images:/app/images
      # 可挂载自定义的配置文件快速进行系统配置
      #- F:\Docker\terra\server/appsettings.json:/app/appsettings.json
      |
      要更改为： - 自定义路径:/app/images

之后启动的时候会提示139报错。无视即可。现在已经安装完成了。

后端会有些问题需要进行：

**Comment by wqelinyueting** [comment]
后端会有些问题需要进行： docker run --name terramoursgptadmin1 -p 4226:8081 -e VUE_APP_API_BASE_URL=http://104.128.95.12:3116 --restart always -d raokun88/terramours_gpt_admin:latest   

然后使用4226端口进行进入（自定义）

**Comment by wqelinyueting** [comment]
admin:
    image: raokun88/terramours_gpt_admin:latest
    container_name: terramoursgptadmin
    environment:
      - VUE_APP_API_BASE_URL=http://XXX改成自己的服务器ip:3116
    ports:
      - "3226:8081"
    restart: always
    networks:
      - server

  web:
    image: raokun88/terramours_gpt_web:latest
    container_name: terramoursgptweb
    environment:
      - VUE_APP_API_BASE_URL=http://XXX改成自己的服务器ip:3116

**Comment by wqelinyueting** [comment]
> 报告会有些问题需要进行： docker run --name terramoursgptadmin1 -p 4226:8081 -e VUE_APP_API_BASE_URL= http://104.128.95.12:3116 --restart always -d raokun88/terramours_gpt_admin:latest
> 
> 然后使用4226端口进行进入（自定义）

修改完参数（api-key）需要重启docke容器。建议全部重启一下。基本就可以运行了

**Comment by MaryGroce** [comment]
搞不懂注册和登录也不行

**Comment by raokun** [comment]
注册bug已修复，docker部署需要改的路径已备注。也可以使用appsettings.json文件挂载方式控制后端服务配置。
