### ISSUE TITLE
key不能设置代理地址吗？

### ISSUE THREAD

**Issue by sjkhsl** [TerraMours/TerraMours_Gpt_Web#41]
key不能设置代理地址吗？

**Comment by raokun** [comment]
> key不能设置代理地址吗？

当然可以，请使用最新的镜像。
![I8 9Y{3YA66HX9R0X15BJY0](https://github.com/TerraMours/TerraMours_Gpt_Web/assets/43564692/3485d1df-ccdd-4ada-9bac-cd89b884dce9)
