### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by taurusduan** [TerraMours/TerraMours_Gpt_Web#44]
一直显示“网络不可用”

version: "3.9"
services:
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always
    networks:
      - server

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=terramours1024
      - POSTGRES_DB=TerraMoursGpt
    ports:
      - "54321:5432"
    restart: always
    networks:
      - server

  seq:
    image: datalust/seq
    container_name: seq_container
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    restart: always
    networks:
      - server

  server:
    image: raokun88/terramours_gpt_server:latest
    container_name: terramours_gpt_server
    environment:
      - TZ=Asia/Shanghai
      - ENV_DB_CONNECTION=Host=postgres;Port=54321;Userid=postgres;password=terramours1024;Database=TerraMoursGpt;
      - ENV_REDIS_HOST=redis:6379
      - ENV_SEQ_HOST=http://192.168.1.110:5341/
    volumes:
      # 图片挂载地址，将容器中的图片挂载出来
      - /path/terra/images:/app/images
      # 可挂载自定义的配置文件快速进行系统配置
      #- F:\Docker\terra\server/appsettings.json:/app/appsettings.json
    ports:
      - "3116:80"
    restart: always
    networks:
      - server
    depends_on:
      - postgres
      - redis
  admin:
    image: raokun88/terramours_gpt_admin:latest
    container_name: terramoursgptadmin
    environment:
      - VUE_APP_API_BASE_URL=http://192.168.1.110:3116
    ports:
      - "3226:8081"
    restart: always
    networks:
      - server

  web:
    image: raokun88/terramours_gpt_web:latest
    container_name: terramoursgptweb
    environment:
      - VUE_APP_API_BASE_URL=http://192.168.1.110:3116
    ports:
      - "3216:8081"
    restart: always
    networks:
      - server

networks:
  server:
    driver:
      bridge

使用的是Debian10，宝塔。也按照要求重启服务器。但是还是登陆不上去，显示网络不可用

**Comment by taurusduan** [comment]
Windows版本，不知道为什么server一直在启动

**Comment by raokun** [comment]
你可以检查一下容器日志

**Comment by taurusduan** [comment]
> 您可以检查一下集装箱日志

问题找到了，我这边修改了5432映射端口，但是似乎没有生效，我修改了其他项目的5432端口，现在服务器端不会重启了，但是我使用terramours@163.com登陆提示密码错误

**Comment by raokun** [comment]
> > 您可以检查一下集装箱日志
> 
> 
> 
> 问题找到了，我这边修改了5432映射端口，但是似乎没有生效，我修改了其他项目的5432端口，现在服务器端不会重启了，但是我使用terramours@163.com登陆提示密码错误
> 
> 

查看Server服务容器，数据库弄好后，在Server启动时会初始化数据库的基础数据，请尝试重启Server容器，具体的查看terramours.site

**Comment by taurusduan** [comment]
> > > 您可以检查一下集装箱日志
> > 
> > 
> > 问题找到了，我这边修改了5432映射端口，但是似乎没有生效，我修改了其他项目的5432端口，现在服务器端不会重启了，但是我使用[terramours@163.com](mailto:terramours@163.com)登陆提示密码错误
> 
> 查看Server服务容器，数据库弄好后，在Server启动时会初始化数据库的基础数据，请尝试重启Server容器，具体的查看terramours.site

OK，搞定了。大哥，后台设计的很漂亮。

**Comment by raokun** [comment]
谢谢支持，问题解决，issue我关闭了
