### ISSUE TITLE
关于请求方法未允许

### ISSUE THREAD

**Issue by sfwjnpw1** [TerraMours/TerraMours_Gpt_Web#48]
跑完 dockercompose 后前后端登录都是请求方法未允许 405，已经重启了 server 容器。yml 文件修改了本地地址和图片地址。
另外请教一下，跑完 yam 文件后npnm 命令和 docker 命令还需要执行吗。
![截屏2024-01-26 21 16 52](https://github.com/TerraMours/TerraMours_Gpt_Web/assets/86069797/d181bea6-c1d5-4478-9f1a-909556218de5)
![截屏2024-01-26 21 17 44](https://github.com/TerraMours/TerraMours_Gpt_Web/assets/86069797/d04eff9a-9e1f-4938-b1a2-f8643c9793ee)

**Comment by raokun** [comment]
那应该是后端接口调用失败，F12检查下浏览器调用的后端接口的端口是否对应的上

**Comment by sfwjnpw1** [comment]
yml 文件还需要修改端口吗，我的 3116 端口无法访问
![截屏2024-01-27 19 32 30](https://github.com/TerraMours/TerraMours_Gpt_Web/assets/86069797/6f9ded98-e689-44ea-8618-72ae51dcf3fe)

**Comment by raokun** [comment]
API地址重复了，你这localhost后面又有IP，不是正确的地址
